### PR TITLE
Explanation in Readme.md

### PR DESCRIPTION
**Pull request by raaaimund**
Just added the explanation to the Readme.md file.

### CODE REVIEW

**Comment by galexrt** [comment]
@raaaimund Thanks for the contribution.
Please rebase your commits.

**Comment by raaaimund** [comment]
Sorry, had some problems to figure out how to do rebases - first rebase was a mess ^^

**Comment by galexrt** [comment]
@raaaimund How did you rebase? It doesn't look like you squashed your commits into one. Could you retry please.

**Comment by galexrt** [comment]
@raaaimund Even this PR isn't correctly rebased, I'm merging but going to make some changes to it.

Thanks for the PR!

**Comment by raaaimund** [comment]
Sorry that this answer is so late.
I rebased after this tutorial.
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

with
`git rebase -i HEAD~n`
i rebased all my previous commits and in the interactive rebasing i replaced all 'pick' with 'squash' except the first 'pick'.

I had to merge many times and in the end I had again 4 additional commits ...

**Comment by galexrt** [comment]
No problem, I've merged it no matter the commit looked now ;)
Thanks for the PR!

**Pull request merged**
